"""Connect an initialized project's normal task flow to automatic closeout.

Only workflow/AGENTS instructions are migrated. Originals are backed up outside
the project. No task, journal, spec, business source, or Git configuration changes.
"""
from __future__ import annotations

import argparse
from collections import deque
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import stat
import tempfile


START = "<!-- TRELLIS-SKILLS:AUTOFINISH:START -->"
END = "<!-- TRELLIS-SKILLS:AUTOFINISH:END -->"
ROUTE_PREFIX = "Automatic closeout (trellis-skills):"
ROUTE = (
    ROUTE_PREFIX + " when the main session has finished this task's implementation, "
    "checks, spec updates and authorized code commits, invoke trellis-finish-work "
    "in this turn and wait for its full trellis-check before archive/journal/final "
    "completion. Do not wait for another user message or status=completed. "
    "Check/implement sub-agents return their result to the main session; they do not archive."
)
BLOCK = f"""{START}
## Automatic Trellis task closeout

For a normal coding task in this initialized project, the main session owns
the entire task flow. Read the selected Trellis workflow and applicable skills.
Once the requested implementation is complete, continue through verification,
spec updates when needed, authorized code commits, and `trellis-finish-work`
before the final completion reply. Do not stop at "you can run finish-work" or
wait for the user to say "finish" again. The task may still be `in_progress`:
archive changes its status, so `completed` is not the trigger for closeout.

At the finish entry, load `trellis-finish-work` from the available project or
global skills; it invokes `trellis-check` and waits for the actual full result.
Resolve skills by their installed location, not an assumed root `skills/` folder.
If those skills are missing, report the setup failure instead of claiming completion.
Check the complete affected scope, fix failures and retest before archive/journal.
Record actual commands, results and the tested revision or working diff in the
task evidence; a context manifest such as `check.jsonl` is not a test result.

This is a main-session route. Delegated implement/check agents return their
results without archiving tasks or invoking recursive closeout. Questions,
progress updates, unfinished work, user pauses/stops, and an explicit Trellis
opt-out do not trigger closeout. Honor existing user authorization for commits
and publication; closeout does not grant new permission. If the user requested
no commit, complete verification and report that archive remains pending.

Within the same closeout attempt, keep a passing full-check result when only
archive/journal bookkeeping remains. Repeat affected checks after fixes, and
repeat the full gate when code or check inputs changed. A GitHub push request
alone is not a new quality-check trigger. Use plain-language README/Release
notes when publishing; do not create a Release unless publication scope includes it.

This block supplements project-specific instructions and replaces the old
manual wrap-up reminder. It is an AI workflow instruction, not an application
idle/close hook or a background GitHub watcher.
{END}
"""
GLOBAL_START = "<!-- TRELLIS-SKILLS:GLOBAL-AUTOFINISH:START -->"
GLOBAL_END = "<!-- TRELLIS-SKILLS:GLOBAL-AUTOFINISH:END -->"
GLOBAL_BLOCK = f"""{GLOBAL_START}
## Trellis projects only

Apply this section only when the current coding project contains
`.trellis/workflow.md` and the user has not opted out of Trellis. Other projects,
questions, progress updates and paused/stopped work are outside its scope.

Before following a newly initialized or older project's workflow, check for
`TRELLIS-SKILLS:AUTOFINISH:START` in its `AGENTS.md` and selected workflow.
If missing, run the current global helper with the actual project root:

`python <user-profile>/.agents/skills/trellis-setup/scripts/upgrade_project.py --project-root <project-root> --sync-skills --register`

Resolve the user's real profile path. The helper backs up old instructions,
preserves project rules and data, connects automatic closeout, and refreshes
older project skill templates generated by `trellis init`. Reread the upgraded
project instructions. If it fails, report the failure instead of assuming readiness.

In a normal coding task, the main session continues from completed implementation
and authorized code commits into `trellis-finish-work` before its final completion
reply, without asking the user to repeat a finish command. Wait for its real full
`trellis-check`, fix failures and retest, then archive and record the session.
Delegated implement/check agents return their results and do not archive.
An app idle/close event or a GitHub push-only request is not a new gate trigger.
Preserve the user's existing authorization and any explicit stop or opt-out.
{GLOBAL_END}
"""


def profile_dir() -> Path:
    return Path(os.environ.get("USERPROFILE") or Path.home())


def discover_projects(roots: list[Path]) -> dict:
    """Use cached directory entries instead of a PowerShell pipeline per folder."""
    pending = deque(root.absolute() for root in roots)
    visited = set()
    projects, skills, missing = [], [], []
    excluded = {"node_modules", ".git", ".trellis", ".agents", ".codex", "__pycache__", ".venv", "venv"}
    while pending:
        current = pending.popleft()
        identity = os.path.normcase(str(current))
        if identity in visited:
            continue
        visited.add(identity)
        if not current.exists():
            missing.append(str(current))
            continue
        if has_link(current, current):
            continue
        with os.scandir(current) as entries:
            for entry in entries:
                if not entry.is_dir(follow_symlinks=False):
                    continue
                attributes = getattr(entry.stat(follow_symlinks=False), "st_file_attributes", 0)
                if attributes & getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0x400):
                    continue
                path = Path(entry.path)
                if entry.name == ".trellis" and (path / "workflow.md").is_file():
                    projects.append(str(current))
                if entry.name in (".agents", ".codex"):
                    target = path / "skills"
                    if target.is_dir() and not has_link(target, path):
                        with os.scandir(target) as children:
                            if any(child.name.startswith("trellis-") and child.is_dir(follow_symlinks=False) for child in children):
                                skills.append(str(target))
                if entry.name.lower() not in excluded:
                    pending.append(path)
    return {"Skills": sorted(set(skills)), "Projects": sorted(set(projects)), "Missing": missing, "Directories": len(visited)}


def has_link(path: Path, root: Path) -> bool:
    """Reject symlinks/junctions in any existing part of a managed path."""
    for item in (path, *path.parents):
        if item.is_symlink() or (hasattr(item, "is_junction") and item.is_junction()):
            return True
        try:
            if getattr(item.lstat(), "st_file_attributes", 0) & getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0x400):
                return True
        except FileNotFoundError:
            pass
        if item == root:
            break
    return False


def decode(raw: bytes) -> tuple[str, str, bool]:
    bom = raw.startswith(b"\xef\xbb\xbf")
    text = raw.decode("utf-8-sig")
    newline = "\r\n" if "\r\n" in text else "\n"
    return text.replace("\r\n", "\n"), newline, bom


def managed_block(text: str, block: str = BLOCK, start: str = START, end: str = END) -> str:
    if text.count(start) != text.count(end) or text.count(start) > 1:
        raise ValueError("Invalid automatic-closeout markers; preserve file for manual review")
    if start in text:
        if text.index(end) < text.index(start):
            raise ValueError("Reversed automatic-closeout markers")
        return re.sub(re.escape(start) + r".*?" + re.escape(end),
                      lambda _: block.rstrip("\n"), text, flags=re.S)
    return text + ("\n" if text.endswith("\n") else "\n\n") + block


def migrate_workflow(text: str) -> str:
    text = text.replace("- 3.5 Wrap-up reminder", "- 3.5 Automatic wrap-up `[required]`")
    text = text.replace("#### 3.5 Wrap-up reminder", "#### 3.5 Automatic wrap-up")
    old = "After the above, remind the user they can run `/finish-work` to wrap up (archive the task, record the session)."
    text = text.replace(old, "After the above, the main session automatically invokes `trellis-finish-work` in the same turn. Wait for its full quality check; only after success archive the task and record the session. Do not end with a reminder asking the user to invoke it.")
    for state in ("in_progress", "in_progress-inline", "completed"):
        pattern = re.compile(r"(^[ \t]*\[workflow-state:" + re.escape(state) + r"\][ \t]*\n)(.*?)(^[ \t]*\[/workflow-state:" + re.escape(state) + r"\][ \t]*(?=\n|$))", re.S | re.M)
        def update(match: re.Match) -> str:
            body = re.sub(r"(?m)^" + re.escape(ROUTE_PREFIX) + r"[^\n]*\n?", "", match[2])
            return match[1] + body.rstrip("\n") + "\n" + ROUTE + "\n" + match[3]
        text = pattern.sub(update, text)
    return managed_block(text)


def atomic_write(path: Path, raw: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=".trellis-upgrade-", dir=path.parent)
    try:
        with os.fdopen(fd, "wb") as output:
            output.write(raw)
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def upgrade(project_root: Path, backup_root: Path, check: bool = False) -> dict:
    root = project_root.absolute()
    if has_link(root, root):
        raise ValueError("Project root must not be a symbolic link or junction")
    workflow = root / ".trellis" / "workflow.md"
    if not workflow.is_file():
        raise ValueError(f"Initialized Trellis workflow not found: {workflow}")
    files = [workflow, *sorted((root / ".trellis" / "workflows").glob("*.md")), root / "AGENTS.md"]
    changes = []
    # Validate and prepare every file before changing any of them.
    for path in files:
        if has_link(path, root):
            raise ValueError(f"Managed file must not traverse a link: {path}")
        old = path.read_bytes() if path.exists() else b""
        text, newline, bom = decode(old)
        updated = managed_block(text) if path.name == "AGENTS.md" else migrate_workflow(text)
        new = updated.replace("\n", newline).encode("utf-8-sig" if bom else "utf-8")
        if old != new:
            changes.append((path, old, new, path.exists()))
    return apply_changes(root, changes, backup_root, check)


def apply_changes(root: Path, changes: list, backup_root: Path, check: bool) -> dict:
    backups = []
    if not check:
        for path, old, _, existed in changes:
            if not existed:
                continue
            identity = hashlib.sha256(str(path).encode("utf-8")).hexdigest()[:20]
            digest = hashlib.sha256(old).hexdigest()
            backup = backup_root / identity / (digest + ".bak")
            if not backup.exists():
                atomic_write(backup, old)
                atomic_write(backup.with_suffix(".json"), json.dumps({"original": str(path), "sha256": digest}, ensure_ascii=False).encode("utf-8"))
            backups.append(str(backup))
        for path, old, new, existed in changes:
            # Do not overwrite concurrent project edits made after planning.
            if path.exists() != existed or (existed and path.read_bytes() != old):
                raise RuntimeError(f"File changed during upgrade; retry: {path}")
            atomic_write(path, new)
    return {"project": str(root), "status": "needs-upgrade" if changes and check else "updated" if changes else "current",
            "files": [str(p.relative_to(root)) for p, *_ in changes], "backups": backups}


def upgrade_global_rules(profile: Path, backup_root: Path, check: bool = False) -> dict:
    root = profile.absolute()
    path = root / ".codex/AGENTS.md"
    if has_link(path, root):
        raise ValueError(f"Global instruction path must not traverse a link: {path}")
    old = path.read_bytes() if path.exists() else b""
    text, newline, bom = decode(old)
    new = managed_block(text, GLOBAL_BLOCK, GLOBAL_START, GLOBAL_END).replace("\n", newline).encode("utf-8-sig" if bom else "utf-8")
    changes = [(path, old, new, path.exists())] if old != new else []
    return apply_changes(root, changes, backup_root, check)


def remove_global_rules(profile: Path, backup_root: Path) -> dict:
    root = profile.absolute()
    path = root / ".codex/AGENTS.md"
    if has_link(path, root):
        raise ValueError(f"Global instruction path must not traverse a link: {path}")
    if not path.exists():
        return apply_changes(root, [], backup_root, False)
    old = path.read_bytes()
    text, newline, bom = decode(old)
    # Validate markers before removing our block; leave all other user rules.
    managed_block(text, GLOBAL_BLOCK, GLOBAL_START, GLOBAL_END)
    updated = re.sub(r"\n?" + re.escape(GLOBAL_START) + r".*?" + re.escape(GLOBAL_END) + r"\n?", "", text, flags=re.S)
    new = updated.replace("\n", newline).encode("utf-8-sig" if bom else "utf-8")
    return apply_changes(root, [(path, old, new, True)] if old != new else [], backup_root, False)


def sync_skills(project_root: Path, source: Path) -> None:
    """Use after trellis init, which can install older project skill templates."""
    skills = [p for p in source.glob("trellis-*") if p.is_dir() and (p / "SKILL.md").is_file()]
    if not skills:
        raise ValueError(f"No source Trellis skills at {source}")
    for kind in (".agents", ".codex"):
        target = project_root / kind / "skills"
        if not target.is_dir():
            continue
        if has_link(target, project_root):
            raise ValueError(f"Skill target must not traverse a link: {target}")
        for skill in skills:
            dest = target / skill.name
            if has_link(dest, project_root):
                raise ValueError(f"Skill target must not be a link: {dest}")
            if dest.exists() and any(has_link(p, dest) for p in dest.rglob("*")):
                raise ValueError(f"Skill contents must not contain links: {dest}")
            if dest.resolve() != skill.resolve():
                shutil.copytree(skill, dest, dirs_exist_ok=True, ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))


def register(root: Path, registry: Path) -> None:
    data = json.loads(registry.read_text(encoding="utf-8-sig")) if registry.exists() else {"version": 1, "projects": []}
    projects = data.get("projects", []) if isinstance(data, dict) else data
    if not isinstance(projects, list) or not all(isinstance(p, str) for p in projects):
        raise ValueError("Invalid project registry")
    if not any(os.path.normcase(p) == os.path.normcase(str(root)) for p in projects):
        projects.append(str(root))
    atomic_write(registry, json.dumps({"version": 1, "projects": projects}, ensure_ascii=False, indent=2).encode("utf-8"))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", type=Path, default=Path.cwd())
    parser.add_argument("--backup-root", type=Path, default=profile_dir() / ".trellis-skills" / "backups")
    parser.add_argument("--registry-path", type=Path, default=profile_dir() / ".trellis-skills" / "projects.json")
    parser.add_argument("--register", action="store_true")
    parser.add_argument("--sync-skills", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--global-rules", action="store_true", help="Install the Trellis-only global Codex entry rule")
    parser.add_argument("--remove-global-rules", action="store_true", help="Remove only the installed Trellis global entry block")
    parser.add_argument("--discover-projects", type=Path, nargs="+", help="Find initialized projects and existing skill roots without following links")
    args = parser.parse_args()
    if args.discover_projects:
        print(json.dumps(discover_projects(args.discover_projects), ensure_ascii=True))
        return
    if args.remove_global_rules:
        if args.check or args.global_rules:
            parser.error("--remove-global-rules cannot be combined with --check or --global-rules")
        print(json.dumps(remove_global_rules(profile_dir(), args.backup_root), ensure_ascii=True))
        return
    if args.global_rules:
        result = upgrade_global_rules(profile_dir(), args.backup_root, args.check)
        print(json.dumps(result, ensure_ascii=True))
        return
    if args.check:
        result = upgrade(args.project_root, args.backup_root, True)
    else:
        # Validate first; write readiness markers only after all setup phases
        # that can fail (skill refresh and registration) have succeeded.
        upgrade(args.project_root, args.backup_root, True)
        if args.sync_skills:
            sync_skills(args.project_root.absolute(), Path(__file__).resolve().parents[2])
        if args.register:
            register(args.project_root.absolute(), args.registry_path)
        result = upgrade(args.project_root, args.backup_root, False)
    print(json.dumps(result, ensure_ascii=True))


if __name__ == "__main__":
    main()
